### ISSUE TITLE
Clues with italics / bold treated as "starred entries"

### ISSUE THREAD

**Issue by Aurathic** [crosshare-org/crosshare#474] opened 2024-03-01 18:47 UTC
If an answer has a clues with italics and bold, or contains an asterisk somewhere else in the clue besides the start, it is still highlighted when the cursor is on an answer with "starred entries" in the clue. [Here's an example puzzle showing the issue](https://crosshare.org/crosswords/ZjqrvPwluAqOABaWLX3Q/testing). 

Also note that the italic/bold-clue answers function differently when selected: When selecting a normal starred-clue entry, all of the other starred entries are highlighted (and the theme revealer), but when selecting the falsely starred entries only the "properly" starred entries are highlighted (i.e. the ones with an asterisk at the front).

I assume this is because the asterisks used for formatting are incorrectly being treated as stars for starred entries.

**Comment by mdirolf** [comment] 2024-03-01 18:48
Thanks for the report! Closing as duplicate of https://github.com/crosshare-org/crosshare/issues/437

**Closed by mdirolf** 2024-03-01 18:48 UTC
