### ISSUE TITLE
Unexpected behavior with spoiler text in clues on iPad

### ISSUE THREAD

**Issue by revuluri** [crosshare-org/crosshare#472] opened 2024-02-20 03:21 UTC
> That was tough without the nudges. And in fact I didn’t get a chance to do that; a funny thing, maybe unique to this platform (my iPad, tested this on Safari or Chrome), is that once I filled in all the letter to one answer, the nudge was visible. The black block was still there in the clue, but the text was now gray, and could be seen amid the black.

From Larry Edelstein here: https://crosshare.org/crosswords/xEOMnY5Qyrdrkt0aagtv/mini-18

**Comment by mdirolf** [comment] 2024-02-20 18:26
Hmm I'm unable to reproduce - have you managed to?

**Comment by revuluri** [comment] 2024-02-21 13:10
Sorry, no! I just wanted to move it from a comment on a random puzzle into the issues list. I will try today when not logged in as me.On Feb 20, 2024, at 12:26 PM, Mike Dirolf ***@***.***> wrote:﻿
Hmm I'm unable to reproduce - have you managed to?

**Comment by mdirolf** [comment] 2024-02-21 16:32
No worries! This is definitely the right place for an issue like that. I'll leave it open for a bit to see if you or anybody else is able to reproduce it.

**Comment by mdirolf** [comment] 2024-03-15 15:58
Closing until we have a reproduction as I've been unable to.

**Closed by mdirolf** 2024-03-15 15:58 UTC
