### ISSUE TITLE
Autofill not working about half the time

### ISSUE THREAD

**Issue by elle-trudgett** [crosshare-org/crosshare#456] opened 2023-10-20 18:50 UTC
I've noticed that every other new puzzle I start creating, the autofill will show the "running" animation (perpetually) but no letters show up. E.g. in a new 5x5 crossword. It starts working again if I refresh the page / re-launch the constructor.

**Comment by elle-trudgett** [comment] 2023-10-20 19:10
Screen recording exhibiting the issue.

https://github.com/crosshare-org/crosshare/assets/6572020/b4314b6b-09c3-4a10-ab4a-3926581e12ec

**Comment by mdirolf** [comment] 2023-10-20 19:29
Thanks for the issue and especially for the video that helps explain what you're seeing.

I am unable to reproduce this - what browser/OS are you on? Is there any chance you can check your browser's Javascript console for any error messages during one of the times you're experiencing this behavior?

**Comment by elle-trudgett** [comment] 2023-10-24 18:23
Unable to reproduce it on demand, and when it happens I instinctively hit refresh since it's just muscle memory now. Argh! I'll try to get console logs soon, haha

**Comment by elle-trudgett** [comment] 2023-11-13 19:55
I notice that the console is saying the autofiller is finishing, but the UI is not reflecting it.

![image](https://github.com/crosshare-org/crosshare/assets/6572020/182d169a-e756-4986-8ab8-7b68c422fd2f)

**Comment by elle-trudgett** [comment] 2023-11-13 19:55
Console log upon refresh (it's working here)

![image](https://github.com/crosshare-org/crosshare/assets/6572020/0b7f04ba-5e39-4ab3-a8ad-297167324f07)

**Comment by elle-trudgett** [comment] 2023-11-13 20:09
Here is a full log from after clicking "Launch Constructor"

![image](https://github.com/crosshare-org/crosshare/assets/6572020/a7e0907f-6aed-490d-a9e6-76ab72a2a32a)

And another:

![image](https://github.com/crosshare-org/crosshare/assets/6572020/253bb64e-31e6-402a-b362-facd3a30a0c2)

I tried in two separate tabs (which were both open while the autofiller was working) and neither autofiller worked. It happened after I successfully published a puzzle and it went through the new puzzle creation workflow (choose a size, etc.)

**Comment by mdirolf** [comment] 2023-11-15 21:36
Hmm thank you for the details! I'm still at a bit of a loss here w/o being able to reproduce. Maybe I'll have to try in some other browser/os combos but I'm somewhat limited w/ access.

**Comment by elle-trudgett** [comment] 2023-11-16 18:33
Reproduction steps:

1. Open Crosshare.org in a Chromium-based browser
2. Sign in with Google
3. Open constructor, download word list and create a new 5x5 puzzle
4. **Autofiller is working**
5. Fill the puzzle, fill in the clues, and the crossword title and publish it
6. Click "Crosshare" in the top left to get back to the home page
7. Click Constructor Dashboard
8. Click create a new puzzle again, choose 5x5
9. **Autofiller does not work**

**Comment by mdirolf** [comment] 2023-11-16 23:50
Thank you @elle-trudgett - managed to reproduce following your steps. Haven't had a chance to dive in and figure things out yet but I'm confident we can address it :)

**Comment by elle-trudgett** [comment] 2023-11-17 18:01
Seems to be related to clicking the "CROSSHARE" logo in the top left. I don't even need to publish a puzzle to reproduce it:


https://github.com/crosshare-org/crosshare/assets/6572020/22f294d7-552e-4ae9-8fec-b03608d4b95d

**Comment by mdirolf** [comment] 2023-11-17 18:05
Yeah I should've mentioned to save you the trouble but I was able to reproduce w/o the publish step as well.

**Comment by elle-trudgett** [comment] 2023-11-17 22:24
It's got to have something to do with the react hook dangling, or something right? 😅

It's firing the events to update the autofilled grid and say that autofilling is done, but nothing's showing up on the page.

https://github.com/crosshare-org/crosshare/blob/d093d30daf02f21984cd25d5f5122d80e25d78a0/app/components/Builder.tsx#L410

**Comment by mdirolf** [comment] 2023-11-17 23:29
Yeah seems we're about at the same place in our debugging efforts. `setAutofilledGrid` is getting called in the callback w/ the correct data but for some reason `autofilledGrid` is never getting updated. Something screwy maybe when the builder component gets mounted the second time around (since it only seems to happen when you navigate away from the constructor and then back w/o doing any reload)

**Comment by mdirolf** [comment] 2023-11-18 00:32
I think I have found the problem - will try to code up a reasonable fix tmrw. There is a module-level variable `worker` that gets initialized in that callback but then doesn't get re-initialized when the component remounts. The worker then has references to the old `setAutofilledGrid` function.

It makes me wonder if this is even a regression or if it was never working at all.

**Comment by mdirolf** [comment] 2023-11-19 19:12
Just deployed the above fix - I'm going to close this but please re-open if you notice anything weird @elle-trudgett

**Closed by mdirolf** 2023-11-19 19:12 UTC

**Comment by elle-trudgett** [comment] 2023-11-20 16:24
Will do, thanks Mike!
